version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: aws110/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: aws110/restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: aws110/restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: aws110/frontend
